Feat/key
GeekyAnts/react-pluggable pull request #16
Opened 2020-12-03 09:26 UTC by amars29

2020-12-03 09:53 UTC, Ajamuar requested changes

2020-12-03 09:53 UTC, Ajamuar commented on src/plugins/RendererPlugin/components/Renderer.tsx
>        {components.map((Component: any) => (
**Change (Blocking)**: Do not use any. 
**Suggestion**: Use better variable name such as `componentsDataArray`.
**Suggestion** Take component inside the map in a variable and then use that variable

2020-12-03 09:53 UTC, Ajamuar commented on src/plugins/RendererPlugin/index.tsx
> +    Array<{ component: React.Component; key?: string }>
**Suggestion (non-blocking)**: Let's declare the type in types folder of `RendererPlugin` and use it from there.

2020-12-03 09:53 UTC, Ajamuar commented on src/plugins/RendererPlugin/index.tsx
> +    key?: String
**Suggestion (non-blocking):** key not needed here

2020-12-03 09:53 UTC, Ajamuar commented on src/plugins/RendererPlugin/index.tsx
> +      key
**Suggestion (non-blocking)**: Search only using component

2020-12-03 09:53 UTC, Ajamuar commented on src/plugins/RendererPlugin/uuid.ts
> +var uuid = require('react-uuid');
**Change:** Never use `var`

2021-02-11 13:30 UTC, himanshu-satija approved these changes

2021-02-11 13:31 UTC, merged